ALTER TABLE matches ADD COLUMN IF NOT EXISTS venue_city text;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS venue_name text;

UPDATE matches SET venue_city='Mexico City', venue_name='Estadio Banorte' WHERE id=1;
UPDATE matches SET venue_city='Guadalajara', venue_name='Estadio Akron' WHERE id=2;
UPDATE matches SET venue_city='Toronto', venue_name='BMO Field' WHERE id=3;
UPDATE matches SET venue_city='Inglewood, California', venue_name='SoFi Stadium' WHERE id=4;
UPDATE matches SET venue_city='Santa Clara, California', venue_name='Levi''s Stadium' WHERE id=5;
UPDATE matches SET venue_city='East Rutherford, New Jersey', venue_name='MetLife Stadium' WHERE id=6;
UPDATE matches SET venue_city='Foxborough, Massachusetts', venue_name='Gillette Stadium' WHERE id=7;
UPDATE matches SET venue_city='Vancouver', venue_name='BC Place' WHERE id=8;
UPDATE matches SET venue_city='Houston, Texas', venue_name='NRG Stadium' WHERE id=9;
UPDATE matches SET venue_city='Arlington, Texas', venue_name='AT&T Stadium' WHERE id=10;
UPDATE matches SET venue_city='Philadelphia, Pennsylvania', venue_name='Lincoln Financial Field' WHERE id=11;
UPDATE matches SET venue_city='Guadalupe', venue_name='Estadio BBVA' WHERE id=12;
UPDATE matches SET venue_city='Atlanta, Georgia', venue_name='Mercedes-Benz Stadium' WHERE id=13;
UPDATE matches SET venue_city='Seattle, Washington', venue_name='Lumen Field' WHERE id=14;
UPDATE matches SET venue_city='Miami Gardens, Florida', venue_name='Hard Rock Stadium' WHERE id=15;
UPDATE matches SET venue_city='Inglewood, California', venue_name='SoFi Stadium' WHERE id=16;
UPDATE matches SET venue_city='East Rutherford, New Jersey', venue_name='MetLife Stadium' WHERE id=17;
UPDATE matches SET venue_city='Foxborough, Massachusetts', venue_name='Gillette Stadium' WHERE id=18;
UPDATE matches SET venue_city='Kansas City, Missouri', venue_name='GEHA Field at Arrowhead Stadium' WHERE id=19;
UPDATE matches SET venue_city='Santa Clara, California', venue_name='Levi''s Stadium' WHERE id=20;
UPDATE matches SET venue_city='Houston, Texas', venue_name='NRG Stadium' WHERE id=21;
UPDATE matches SET venue_city='Arlington, Texas', venue_name='AT&T Stadium' WHERE id=22;
UPDATE matches SET venue_city='Toronto', venue_name='BMO Field' WHERE id=23;
UPDATE matches SET venue_city='Mexico City', venue_name='Estadio Banorte' WHERE id=24;
UPDATE matches SET venue_city='Atlanta, Georgia', venue_name='Mercedes-Benz Stadium' WHERE id=25;
UPDATE matches SET venue_city='Inglewood, California', venue_name='SoFi Stadium' WHERE id=26;
UPDATE matches SET venue_city='Vancouver', venue_name='BC Place' WHERE id=27;
UPDATE matches SET venue_city='Guadalajara', venue_name='Estadio Akron' WHERE id=28;
UPDATE matches SET venue_city='Seattle, Washington', venue_name='Lumen Field' WHERE id=29;
UPDATE matches SET venue_city='Foxborough, Massachusetts', venue_name='Gillette Stadium' WHERE id=30;
UPDATE matches SET venue_city='Philadelphia, Pennsylvania', venue_name='Lincoln Financial Field' WHERE id=31;
UPDATE matches SET venue_city='Santa Clara, California', venue_name='Levi''s Stadium' WHERE id=32;
UPDATE matches SET venue_city='Houston, Texas', venue_name='NRG Stadium' WHERE id=33;
UPDATE matches SET venue_city='Toronto', venue_name='BMO Field' WHERE id=34;
UPDATE matches SET venue_city='Kansas City, Missouri', venue_name='GEHA Field at Arrowhead Stadium' WHERE id=35;
UPDATE matches SET venue_city='Guadalupe', venue_name='Estadio BBVA' WHERE id=36;
UPDATE matches SET venue_city='Atlanta, Georgia', venue_name='Mercedes-Benz Stadium' WHERE id=37;
UPDATE matches SET venue_city='Inglewood, California', venue_name='SoFi Stadium' WHERE id=38;
UPDATE matches SET venue_city='Miami Gardens, Florida', venue_name='Hard Rock Stadium' WHERE id=39;
UPDATE matches SET venue_city='Vancouver', venue_name='BC Place' WHERE id=40;
UPDATE matches SET venue_city='Arlington, Texas', venue_name='AT&T Stadium' WHERE id=41;
UPDATE matches SET venue_city='Philadelphia, Pennsylvania', venue_name='Lincoln Financial Field' WHERE id=42;
UPDATE matches SET venue_city='East Rutherford, New Jersey', venue_name='MetLife Stadium' WHERE id=43;
UPDATE matches SET venue_city='Santa Clara, California', venue_name='Levi''s Stadium' WHERE id=44;
UPDATE matches SET venue_city='Houston, Texas', venue_name='NRG Stadium' WHERE id=45;
UPDATE matches SET venue_city='Foxborough, Massachusetts', venue_name='Gillette Stadium' WHERE id=46;
UPDATE matches SET venue_city='Toronto', venue_name='BMO Field' WHERE id=47;
UPDATE matches SET venue_city='Guadalajara', venue_name='Estadio Akron' WHERE id=48;
UPDATE matches SET venue_city='Seattle, Washington', venue_name='Lumen Field' WHERE id=49;
UPDATE matches SET venue_city='Vancouver', venue_name='BC Place' WHERE id=50;
UPDATE matches SET venue_city='Atlanta, Georgia', venue_name='Mercedes-Benz Stadium' WHERE id=51;
UPDATE matches SET venue_city='Miami Gardens, Florida', venue_name='Hard Rock Stadium' WHERE id=52;
UPDATE matches SET venue_city='Mexico City', venue_name='Estadio Banorte' WHERE id=53;
UPDATE matches SET venue_city='Guadalupe', venue_name='Estadio BBVA' WHERE id=54;
UPDATE matches SET venue_city='Philadelphia, Pennsylvania', venue_name='Lincoln Financial Field' WHERE id=55;
UPDATE matches SET venue_city='East Rutherford, New Jersey', venue_name='MetLife Stadium' WHERE id=56;
UPDATE matches SET venue_city='Arlington, Texas', venue_name='AT&T Stadium' WHERE id=57;
UPDATE matches SET venue_city='Kansas City, Missouri', venue_name='GEHA Field at Arrowhead Stadium' WHERE id=58;
UPDATE matches SET venue_city='Santa Clara, California', venue_name='Levi''s Stadium' WHERE id=59;
UPDATE matches SET venue_city='Inglewood, California', venue_name='SoFi Stadium' WHERE id=60;
UPDATE matches SET venue_city='Foxborough, Massachusetts', venue_name='Gillette Stadium' WHERE id=61;
UPDATE matches SET venue_city='Toronto', venue_name='BMO Field' WHERE id=62;
UPDATE matches SET venue_city='Houston, Texas', venue_name='NRG Stadium' WHERE id=63;
UPDATE matches SET venue_city='Guadalajara', venue_name='Estadio Akron' WHERE id=64;
UPDATE matches SET venue_city='Seattle, Washington', venue_name='Lumen Field' WHERE id=65;
UPDATE matches SET venue_city='Vancouver', venue_name='BC Place' WHERE id=66;
UPDATE matches SET venue_city='Philadelphia, Pennsylvania', venue_name='Lincoln Financial Field' WHERE id=67;
UPDATE matches SET venue_city='East Rutherford, New Jersey', venue_name='MetLife Stadium' WHERE id=68;
UPDATE matches SET venue_city='Miami Gardens, Florida', venue_name='Hard Rock Stadium' WHERE id=69;
UPDATE matches SET venue_city='Atlanta, Georgia', venue_name='Mercedes-Benz Stadium' WHERE id=70;
UPDATE matches SET venue_city='Kansas City, Missouri', venue_name='GEHA Field at Arrowhead Stadium' WHERE id=71;
UPDATE matches SET venue_city='Arlington, Texas', venue_name='AT&T Stadium' WHERE id=72;
